In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\Hp\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\Hp\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Hp\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Hp\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\Hp\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\Hp\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\Hp\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Hp\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Hp\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\Hp\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

***Pandas***                                  

Pandas is a powerful Python library used for:                                                   

* Data analysis
* Data cleaning
* Working with tables (Excel/CSV data)
* Handling large datasets

It is one of the most important libraries in:                                                                

* Data Science
* Machine Learning
* AI
* Data Analytics

In [4]:
import os
import numpy as np
import pandas as pd

In [5]:
#######df=data frame

In [6]:
df=pd.read_csv(r"C:\Users\Hp\Downloads\Used_Bikes.csv")

In [7]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [8]:
df.tail(15)

,bike_name,price,city,kms_driven,owner,age,power,brand
32633,Royal Enfield Classic 350cc,87000.0,Gautam Buddha Nagar,16336.0,First Owner,7.0,350.0,Royal Enfield
32634,Royal Enfield Thunderbird 350cc,70000.0,Mumbai,13858.0,Second Owner,11.0,350.0,Royal Enfield
32635,Suzuki Zeus 125cc,35000.0,Ahmedabad,11885.0,First Owner,12.0,125.0,Suzuki
32636,KTM RC 390cc,196700.0,Mumbai,13216.0,First Owner,4.0,390.0,KTM
32637,Bajaj Pulsar 150cc,25000.0,Delhi,32588.0,First Owner,9.0,150.0,Bajaj
32638,Yamaha Fazer 25 250cc,123000.0,Kadapa,14500.0,First Owner,4.0,250.0,Yamaha
32639,Royal Enfield Classic 350cc,95500.0,Delhi,18000.0,First Owner,8.0,350.0,Royal Enfield
32640,Hero Passion Pro 100cc,32000.0,Delhi,12000.0,First Owner,6.0,100.0,Hero
32641,Bajaj Avenger 220cc,41000.0,Delhi,20245.0,Second Owner,11.0,220.0,Bajaj
32642,Hero Passion 100cc,15000.0,Perumbavoor,35000.0,Second Owner,19.0,100.0,Hero
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  str
 1   price       32648 non-null  float64
 2   city        32648 non-null  str
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  str
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  str
dtypes: float64(4), str(4)
memory usage: 2.0 MB

In [10]:
df.columns

Index(['bike_name', 'price', 'city', 'kms_driven', 'owner', 'age', 'power',
       'brand'],
      dtype='str')

In [11]:
df["age"]

0         3.0
1         4.0
2         8.0
3         4.0
4         3.0
         ...
32643     4.0
32644     9.0
32645     6.0
32646    16.0
32647    13.0
Name: age, Length: 32648, dtype: float64

In [12]:
df[["age"]]

        age
0       3.0
1       4.0
2       8.0
3       4.0
4       3.0
...     ...
32643   4.0
32644   9.0
32645   6.0
32646  16.0
32647  13.0

[32648 rows x 1 columns]

In [13]:
df[["age","price"]]

        age     price
0       3.0   35000.0
1       4.0  119900.0
2       8.0  600000.0
3       4.0   65000.0
4       3.0   80000.0
...     ...       ...
32643   4.0   39000.0
32644   9.0   30000.0
32645   6.0   60000.0
32646  16.0   15600.0
32647  13.0   22000.0

[32648 rows x 2 columns]

In [14]:
df["brand"].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [15]:
df["owner"].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [16]:
df["city"].unique()

<StringArray>
[   'Ahmedabad',        'Delhi',    'Bangalore',       'Mumbai',
       'Kalyan',    'Faridabad',       'Mettur',    'Hyderabad',
      'Kaithal',      'Gurgaon',
 ...
  'Bhubaneswar',      'Raiganj', 'Bhilai Nagar',       'Baloda',
     'Anantnag',   'Berhampore',      'Silvasa',       'Hospet',
        'Palai',        'Sidhi']
Length: 443, dtype: str

In [17]:
df["brand"].nunique()

23

In [18]:
df["brand"].value_counts()

brand
Bajaj              11213
Hero                6368
Royal Enfield       4178
Yamaha              3916
Honda               2108
Suzuki              1464
TVS                 1247
KTM                 1077
Harley-Davidson      737
Kawasaki              79
Hyosung               64
Benelli               56
Mahindra              55
Triumph               26
Ducati                22
BMW                   16
Jawa                  10
MV                     4
Indian                 3
Ideal                  2
Rajdoot                1
LML                    1
Yezdi                  1
Name: count, dtype: int64

In [19]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
32643     True
32644     True
32645     True
32646     True
32647     True
Length: 32648, dtype: bool

In [20]:
df.duplicated().sum()

np.int64(25324)

In [21]:
df.drop_duplicates() ###duplicate ko drop krne k liye kaam aati hai

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [22]:
df.duplicated().sum() ####total duplicate value

np.int64(25324)

In [23]:
df.drop_duplicates(inplace=True) ####deplicate row ko permanently delete kr deta hai

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [26]:
df.dropna(inplace = True) ######dropna is used to drop null values

In [27]:

# y = mx +c linear regression

In [28]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7324 non-null   str
 1   price       7324 non-null   float64
 2   city        7324 non-null   str
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   str
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   str
dtypes: float64(4), str(4)
memory usage: 515.0 KB

In [29]:
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [30]:
####decoding :int ko string m convert krna 
####encoding : string ko int m convert krna

In [31]:
# owner_dict ={
#     'First Owner':1, 'Second Owner':2, 'Third Owner':3, 'Fourth Owner Or More':4
# }

In [32]:
# df['owner']=df['owner'].map(owner_dict)##map function used for mapping

In [33]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [34]:
# df.info() #######encoding hui hai

In [35]:
# df.drop('city',axis=1,inplace=True)#axis=1 ka meaning cloumn #axis=0 meaning row
####column permanent delete yah drop krna

In [36]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [37]:
# df.drop(['age','bike_name'],axis=1,inplace=True)

In [38]:
# df

In [39]:
# df['brand'].unique()

In [40]:
# df.info()

In [41]:
# df

In [42]:
# df['brand']=df['brand'].map(brand_dict)

In [43]:
# df

In [44]:
# df.info()

In [45]:
obj_val=df.select_dtypes(include='O')

C:\Users\Hp\AppData\Local\Temp\ipykernel_19464\3000755879.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_val=df.select_dtypes(include='O')

In [46]:
obj_val

,bike_name,city,owner,brand
0,TVS Star City Plus Dual Tone 110cc,Ahmedabad,First Owner,TVS
1,Royal Enfield Classic 350cc,Delhi,First Owner,Royal Enfield
2,Triumph Daytona 675R,Delhi,First Owner,Triumph
3,TVS Apache RTR 180cc,Bangalore,First Owner,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,First Owner,Yamaha
...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,Delhi,First Owner,Hero
9369,Bajaj Avenger 220cc,Bangalore,First Owner,Bajaj
9370,Harley-Davidson Street 750 ABS,Jodhpur,First Owner,Harley-Davidson
9371,Bajaj Dominar 400 ABS,Hyderabad,First Owner,Bajaj
9372,Bajaj Avenger Street 220,Hyderabad,First Owner,Bajaj

In [47]:
num=df.select_dtypes(exclude='O')

In [48]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [49]:
num

         price  kms_driven  age  power
0      35000.0     17654.0  3.0  110.0
1     119900.0     11000.0  4.0  350.0
2     600000.0       110.0  8.0  675.0
3      65000.0     16329.0  4.0  180.0
4      80000.0     10000.0  3.0  150.0
...        ...         ...  ...    ...
9362   25000.0     48587.0  8.0  150.0
9369   35000.0     60000.0  9.0  220.0
9370  450000.0      3430.0  4.0  750.0
9371  139000.0     21300.0  4.0  400.0
9372   80000.0      7127.0  5.0  220.0

[7324 rows x 4 columns]

In [50]:
complete_data=pd.concat([obj_val , num] , axis=1)

In [51]:
complete_data

,bike_name,city,owner,brand,price,kms_driven,age,power
0,TVS Star City Plus Dual Tone 110cc,Ahmedabad,First Owner,TVS,35000.0,17654.0,3.0,110.0
1,Royal Enfield Classic 350cc,Delhi,First Owner,Royal Enfield,119900.0,11000.0,4.0,350.0
2,Triumph Daytona 675R,Delhi,First Owner,Triumph,600000.0,110.0,8.0,675.0
3,TVS Apache RTR 180cc,Bangalore,First Owner,TVS,65000.0,16329.0,4.0,180.0
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,First Owner,Yamaha,80000.0,10000.0,3.0,150.0
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,Delhi,First Owner,Hero,25000.0,48587.0,8.0,150.0
9369,Bajaj Avenger 220cc,Bangalore,First Owner,Bajaj,35000.0,60000.0,9.0,220.0
9370,Harley-Davidson Street 750 ABS,Jodhpur,First Owner,Harley-Davidson,450000.0,3430.0,4.0,750.0
9371,Bajaj Dominar 400 ABS,Hyderabad,First Owner,Bajaj,139000.0,21300.0,4.0,400.0
9372,Bajaj Avenger Street 220,Hyderabad,First Owner,Bajaj,80000.0,7127.0,5.0,220.0

In [52]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [53]:
df[df['brand']=='TVS']

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
52,TVS Apache RTR 160cc,60000.0,Mumbai,30000.0,First Owner,5.0,160.0,TVS
114,TVS Apache RTR 160 4V Disc,69900.0,Delhi,8700.0,First Owner,3.0,160.0,TVS
130,TVS Phoenix Disc 125cc,21500.0,Barasat,10500.0,First Owner,5.0,125.0,TVS
...,...,...,...,...,...,...,...,...
9247,TVS Apache RTR 160cc Rear Disc,70000.0,Ghaziabad,4116.0,First Owner,3.0,160.0,TVS
9307,TVS Apache RTR 160cc,30000.0,Alibag,30000.0,First Owner,10.0,160.0,TVS
9312,TVS Apache RTR 200 4V FI,65450.0,Delhi,9238.0,First Owner,3.0,200.0,TVS
9320,TVS Apache 150cc,20000.0,Hissar,84916.0,First Owner,14.0,150.0,TVS
9322,TVS Radeon 110cc Drum SBT,58000.0,Delhi,4020.0,First Owner,2.0,110.0,TVS

In [54]:
# dup>null value >str>num>drop

In [55]:
# df.isnull().sum()

In [56]:
# df.info()

In [57]:
# df.dropna(inplace=True)

In [58]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [59]:
# df.info()

In [60]:
# df['bike_name'].unique()

In [61]:
bike_name_dict={
    'TVS Star City Plus Dual Tone 110cc':1,
              'Royal Enfield Classic 350cc':2,
                     'Triumph Daytona 675R':3,
                     'TVS Apache RTR 180cc':4,
     'Yamaha FZ S V 2.0 150cc-Ltd. Edition':5,
                         'Yamaha FZs 150cc':6,
            'Honda CB Hornet 160R  ABS DLX':7,
      'Hero Splendor Plus Self Alloy 100cc':8,
        'Royal Enfield Thunderbird X 350cc':9,
 'Royal Enfield Classic Desert Storm 500cc':10,
 
                 'Bajaj Discover150S 150cc':11,
                       'Hero i Smart 125cc':12,
               'Hero Splendor Plus  100 cc':13,
                'Hero Splendor Plus 100 CC':14,
                      'Hero Karizma 223 cc':15,
                         'TVS MAX 4R 110cc':16,
                   'Mahindra Pantero 110cc':17,
                      'Hero Ambition 135cc':18,
                'Honda CBR 250R Repsol ABS':19,
                'Hero Hunk Rear Disc 150cc':20
             
}

In [62]:
# df['bike_name']= df['bike_name'].map(bike_name_dict)

In [63]:
# df

In [64]:
# df.info()

In [65]:
# df.dropna().sum()

In [66]:
# df.isnull().sum()

In [67]:
# df.dropna(inplace=True)

In [68]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [69]:
# df.isnull().sum()

In [70]:
# df.info()

In [71]:
# df.drop('bike_name',axis=1,inplace=True)

In [72]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [73]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [74]:
tvs_brand=df[df['brand']=='TVS']

In [75]:
tvs_under2 =tvs_brand[tvs_brand['age']<=2]

In [76]:
tvs_under2[tvs_under2['kms_driven']<2000]

,bike_name,price,city,kms_driven,owner,age,power,brand
594,TVS Apache RTR 160 4V DISC ABS,91800.0,Delhi,1050.0,First Owner,2.0,160.0,TVS
1126,TVS Apache RTR 200 4V Dual Channel ABS BS6,130000.0,Bangalore,1300.0,First Owner,1.0,200.0,TVS
1132,TVS Apache RTR 160 4V DISC ABS BS6,98000.0,Jaipur,749.0,First Owner,1.0,160.0,TVS
1318,TVS Apache RTR 200 4V ABS Race Edition,125000.0,Hyderabad,530.0,First Owner,2.0,200.0,TVS
1802,TVS Apache RTR 180cc,88000.0,Gurgaon,900.0,First Owner,2.0,180.0,TVS
3071,TVS Apache RTR 160 4V DISC ABS,94000.0,Ahmedabad,893.0,First Owner,2.0,160.0,TVS
5506,TVS Apache RTR 200 4V ABS Race Edition,106000.0,Delhi,1890.0,First Owner,2.0,200.0,TVS
6003,TVS Apache RTR 160 4V Carburetor,90700.0,Delhi,900.0,First Owner,2.0,160.0,TVS

In [77]:
royal_enfield_brand=df[df['brand']=='Royal Enfield']

In [78]:
royal_enfield_under2=royal_enfield_brand[royal_enfield_brand['age']<=2]

In [79]:
royal_enfield_under2[royal_enfield_under2['kms_driven']<2000]

,bike_name,price,city,kms_driven,owner,age,power,brand
277,Royal Enfield Interceptor 650cc,280000.0,Bangalore,1500.0,First Owner,2.0,650.0,Royal Enfield
850,Royal Enfield Himalayan 410cc Fi ABS,180000.0,Guwahati,200.0,First Owner,2.0,410.0,Royal Enfield
962,Royal Enfield Thunderbird X 350cc ABS,155000.0,Vadodara,1650.0,First Owner,2.0,350.0,Royal Enfield
1203,Royal Enfield Classic Gunmetal Grey 350cc ABS,150000.0,Bardhaman,1800.0,First Owner,2.0,350.0,Royal Enfield
1251,Royal Enfield Interceptor 650cc,250000.0,Silchar,920.0,First Owner,2.0,650.0,Royal Enfield
1716,Royal Enfield Thunderbird 350cc ABS,144700.0,Kharar,770.0,First Owner,2.0,350.0,Royal Enfield
1796,Royal Enfield Himalayan 410cc Fi ABS,166000.0,Guwahati,250.0,First Owner,2.0,410.0,Royal Enfield
2929,Royal Enfield Himalayan 410cc Fi ABS,184000.0,Bardhaman,1380.0,First Owner,2.0,410.0,Royal Enfield
3089,Royal Enfield Classic Desert Storm 500cc Dual ...,239000.0,Mumbai,1264.0,First Owner,2.0,500.0,Royal Enfield
3166,Royal Enfield Thunderbird X 350cc ABS,160000.0,Delhi,1189.0,First Owner,2.0,350.0,Royal Enfield
5133,Royal Enfield Thunderbird X 350cc ABS,170000.0,Gurgaon,500.0,First Owner,2.0,350.0,Royal Enfield
5495,Royal Enfield Classic 350cc,150000.0,Kota,1947.0,First Owner,2.0,350.0,Royal Enfield
5703,Royal Enfield Himalayan 410cc Fi ABS,194000.0,Thane,844.0,First Owner,2.0,410.0,Royal Enfield
6022,Royal Enfield Classic Gunmetal Grey 350cc ABS,161100.0,Guwahati,1753.0,First Owner,2.0,350.0,Royal Enfield
6090,Royal Enfield Bullet Electra Twinspark 350CC ABS,127000.0,Mumbai,83.0,First Owner,2.0,350.0,Royal Enfield
6283,Royal Enfield Himalayan 410cc Sleet ABS,175000.0,Alipore,1800.0,First Owner,2.0,410.0,Royal Enfield
7294,Royal Enfield Classic 350cc-Redditch Edition,133500.0,Mumbai,1608.0,First Owner,2.0,350.0,Royal Enfield
7694,Royal Enfield Classic Chrome 500cc ABS,215000.0,Delhi,417.0,First Owner,2.0,500.0,Royal Enfield
8836,Royal Enfield Thunderbird X 350cc ABS,170200.0,Mumbai,1000.0,First Owner,2.0,350.0,Royal Enfield

In [80]:
royal_enfield_under2[royal_enfield_under2['price']<150000]

,bike_name,price,city,kms_driven,owner,age,power,brand
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,First Owner,2.0,350.0,Royal Enfield
1006,Royal Enfield Thunderbird 350cc ABS,148000.0,Haldwani,7300.0,First Owner,2.0,350.0,Royal Enfield
1681,Royal Enfield Thunderbird X 350cc ABS,135000.0,Sibsagar,3800.0,First Owner,2.0,350.0,Royal Enfield
1716,Royal Enfield Thunderbird 350cc ABS,144700.0,Kharar,770.0,First Owner,2.0,350.0,Royal Enfield
1749,Royal Enfield Bullet Twinspark Kickstart 350cc,145000.0,Delhi,5000.0,First Owner,2.0,350.0,Royal Enfield
2982,Royal Enfield Classic 350cc-Redditch Edition,137000.0,Sultanpur,8400.0,First Owner,2.0,350.0,Royal Enfield
5939,Royal Enfield Bullet Twinspark Kickstart 350cc,105000.0,Faridabad,7255.0,First Owner,2.0,350.0,Royal Enfield
6090,Royal Enfield Bullet Electra Twinspark 350CC ABS,127000.0,Mumbai,83.0,First Owner,2.0,350.0,Royal Enfield
6298,Royal Enfield Bullet Electra Twinspark 350CC ABS,140000.0,Mumbai,2000.0,First Owner,2.0,350.0,Royal Enfield
6329,Royal Enfield Electra 350cc,130000.0,Faridabad,3688.0,First Owner,2.0,350.0,Royal Enfield
6590,Royal Enfield Classic 350cc,130000.0,Ghaziabad,19249.0,First Owner,2.0,350.0,Royal Enfield
7019,Royal Enfield Electra 350cc,135000.0,Ahmedabad,10779.0,First Owner,2.0,350.0,Royal Enfield
7294,Royal Enfield Classic 350cc-Redditch Edition,133500.0,Mumbai,1608.0,First Owner,2.0,350.0,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000.0,Ghaziabad,12400.0,First Owner,2.0,350.0,Royal Enfield

In [81]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [82]:
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [83]:
df[(df['brand']=='Royal Enfield') & (df["age"]<=2) & (df['price']<=150000)]

,bike_name,price,city,kms_driven,owner,age,power,brand
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,First Owner,2.0,350.0,Royal Enfield
479,Royal Enfield Classic 350cc,150000.0,Delhi,4000.0,First Owner,2.0,350.0,Royal Enfield
1006,Royal Enfield Thunderbird 350cc ABS,148000.0,Haldwani,7300.0,First Owner,2.0,350.0,Royal Enfield
1203,Royal Enfield Classic Gunmetal Grey 350cc ABS,150000.0,Bardhaman,1800.0,First Owner,2.0,350.0,Royal Enfield
1681,Royal Enfield Thunderbird X 350cc ABS,135000.0,Sibsagar,3800.0,First Owner,2.0,350.0,Royal Enfield
1716,Royal Enfield Thunderbird 350cc ABS,144700.0,Kharar,770.0,First Owner,2.0,350.0,Royal Enfield
1749,Royal Enfield Bullet Twinspark Kickstart 350cc,145000.0,Delhi,5000.0,First Owner,2.0,350.0,Royal Enfield
2982,Royal Enfield Classic 350cc-Redditch Edition,137000.0,Sultanpur,8400.0,First Owner,2.0,350.0,Royal Enfield
5495,Royal Enfield Classic 350cc,150000.0,Kota,1947.0,First Owner,2.0,350.0,Royal Enfield
5939,Royal Enfield Bullet Twinspark Kickstart 350cc,105000.0,Faridabad,7255.0,First Owner,2.0,350.0,Royal Enfield
6090,Royal Enfield Bullet Electra Twinspark 350CC ABS,127000.0,Mumbai,83.0,First Owner,2.0,350.0,Royal Enfield
6298,Royal Enfield Bullet Electra Twinspark 350CC ABS,140000.0,Mumbai,2000.0,First Owner,2.0,350.0,Royal Enfield
6329,Royal Enfield Electra 350cc,130000.0,Faridabad,3688.0,First Owner,2.0,350.0,Royal Enfield
6590,Royal Enfield Classic 350cc,130000.0,Ghaziabad,19249.0,First Owner,2.0,350.0,Royal Enfield
7019,Royal Enfield Electra 350cc,135000.0,Ahmedabad,10779.0,First Owner,2.0,350.0,Royal Enfield
7294,Royal Enfield Classic 350cc-Redditch Edition,133500.0,Mumbai,1608.0,First Owner,2.0,350.0,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000.0,Ghaziabad,12400.0,First Owner,2.0,350.0,Royal Enfield

In [84]:
df.query("brand=='Royal Enfield' and age <=2")

,bike_name,price,city,kms_driven,owner,age,power,brand
38,Royal Enfield Thunderbird X 500cc,190500.0,Samastipur,4550.0,First Owner,2.0,500.0,Royal Enfield
81,Royal Enfield Interceptor 650cc,260000.0,Navi Mumbai,3800.0,First Owner,2.0,650.0,Royal Enfield
139,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,First Owner,2.0,410.0,Royal Enfield
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,First Owner,2.0,350.0,Royal Enfield
222,Royal Enfield Himalayan 410cc Fi ABS,177982.0,Hamirpur(hp),7000.0,First Owner,2.0,410.0,Royal Enfield
...,...,...,...,...,...,...,...,...
7294,Royal Enfield Classic 350cc-Redditch Edition,133500.0,Mumbai,1608.0,First Owner,2.0,350.0,Royal Enfield
7694,Royal Enfield Classic Chrome 500cc ABS,215000.0,Delhi,417.0,First Owner,2.0,500.0,Royal Enfield
8139,Royal Enfield Thunderbird X 350cc ABS,169000.0,Bangalore,4411.0,First Owner,2.0,350.0,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000.0,Ghaziabad,12400.0,First Owner,2.0,350.0,Royal Enfield
8836,Royal Enfield Thunderbird X 350cc ABS,170200.0,Mumbai,1000.0,First Owner,2.0,350.0,Royal Enfield

In [85]:
x=df.drop('price',axis=1)

In [86]:
y=df[['price']]

In [87]:
y

         price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
9362   25000.0
9369   35000.0
9370  450000.0
9371  139000.0
9372   80000.0

[7324 rows x 1 columns]

In [88]:
x

,bike_name,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [89]:
df.to_csv("clean_bike_data.csv")

In [90]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [91]:
df=pd.read_csv(r"C:\Users\Hp\AppData\Local\Packages\5319275A.WhatsAppDesktop_cv1g1gvanyjgm\LocalState\sessions\1A888A513422D7B9363EF4B2C96604499E1209F7\transfers\2026-23\cust_satisfaction.csv")

In [92]:
df

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,Male,Loyal Customer,Personal Travel,Eco Plus,neutral or dissatisfied,13,460,5,4,5,25,18.0
1,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,25,235,1,3,1,1,6.0
2,Female,Loyal Customer,Business travel,Business,satisfied,26,1142,5,4,5,0,0.0
3,Female,Loyal Customer,Business travel,Business,neutral or dissatisfied,25,562,2,3,2,11,9.0
4,Male,Loyal Customer,Business travel,Business,satisfied,61,214,3,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103899,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,23,192,2,4,2,3,0.0
103900,Male,Loyal Customer,Business travel,Business,satisfied,49,2347,5,5,4,0,0.0
103901,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,30,1995,4,4,4,7,14.0
103902,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,22,1000,1,1,1,0,0.0
103903,Male,Loyal Customer,Business travel,Business,neutral or dissatisfied,27,1723,1,4,1,0,0.0