In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\Hp\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\Hp\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Hp\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Hp\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\Hp\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import os
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv(r"C:\Users\Hp\AppData\Local\Packages\5319275A.WhatsAppDesktop_cv1g1gvanyjgm\LocalState\sessions\1A888A513422D7B9363EF4B2C96604499E1209F7\transfers\2026-23\cust_satisfaction.csv")

In [4]:
df

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,Male,Loyal Customer,Personal Travel,Eco Plus,neutral or dissatisfied,13,460,5,4,5,25,18.0
1,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,25,235,1,3,1,1,6.0
2,Female,Loyal Customer,Business travel,Business,satisfied,26,1142,5,4,5,0,0.0
3,Female,Loyal Customer,Business travel,Business,neutral or dissatisfied,25,562,2,3,2,11,9.0
4,Male,Loyal Customer,Business travel,Business,satisfied,61,214,3,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103899,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,23,192,2,4,2,3,0.0
103900,Male,Loyal Customer,Business travel,Business,satisfied,49,2347,5,5,4,0,0.0
103901,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,30,1995,4,4,4,7,14.0
103902,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,22,1000,1,1,1,0,0.0
103903,Male,Loyal Customer,Business travel,Business,neutral or dissatisfied,27,1723,1,4,1,0,0.0

In [5]:
df.tail(15)

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
103889,Female,Loyal Customer,Business travel,Business,satisfied,43,3885,3,3,3,0,0.0
103890,Female,Loyal Customer,Business travel,Eco Plus,satisfied,56,550,3,3,3,0,0.0
103891,Male,Loyal Customer,Business travel,Business,satisfied,54,1991,4,4,4,35,31.0
103892,Female,disloyal Customer,Business travel,Business,neutral or dissatisfied,37,596,3,3,3,110,121.0
103893,Female,Loyal Customer,Business travel,Business,neutral or dissatisfied,58,296,3,3,1,0,29.0
103894,Male,Loyal Customer,Business travel,Business,satisfied,26,712,5,4,5,17,26.0
103895,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,24,1055,1,5,1,13,10.0
103896,Male,Loyal Customer,Business travel,Eco,neutral or dissatisfied,57,867,4,3,4,0,0.0
103897,Female,Loyal Customer,Business travel,Business,satisfied,60,1599,4,4,4,9,7.0
103898,Male,Loyal Customer,Personal Travel,Eco,neutral or dissatisfied,50,1620,2,4,2,0,0.0
103899,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,23,192,2,4,2,3,0.0
103900,Male,Loyal Customer,Business travel,Business,satisfied,49,2347,5,5,4,0,0.0
103901,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,30,1995,4,4,4,7,14.0
103902,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,22,1000,1,1,1,0,0.0
103903,Male,Loyal Customer,Business travel,Business,neutral or dissatisfied,27,1723,1,4,1,0,0.0

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103904 entries, 0 to 103903
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Gender                      103904 non-null  str
 1   Customer Type               103904 non-null  str
 2   Type of Travel              103904 non-null  str
 3   Class                       103904 non-null  str
 4   satisfaction                103904 non-null  str
 5   Age                         103904 non-null  int64
 6   Flight Distance             103904 non-null  int64
 7   Inflight entertainment      103904 non-null  int64
 8   Baggage handling            103904 non-null  int64
 9   Cleanliness                 103904 non-null  int64
 10  Departure Delay in Minutes  103904 non-null  int64
 11  Arrival Delay in Minutes    103594 non-null  float64
dtypes: float64(1), int64(6), str(5)
memory usage: 9.5 MB

In [7]:
df.columns

Index(['Gender', 'Customer Type', 'Type of Travel', 'Class', 'satisfaction',
       'Age', 'Flight Distance', 'Inflight entertainment', 'Baggage handling',
       'Cleanliness', 'Departure Delay in Minutes',
       'Arrival Delay in Minutes'],
      dtype='str')

In [9]:
df["Age"]

0         13
1         25
2         26
3         25
4         61
          ..
103899    23
103900    49
103901    30
103902    22
103903    27
Name: Age, Length: 103904, dtype: int64

In [11]:
df[["Age"]]

        Age
0        13
1        25
2        26
3        25
4        61
...     ...
103899   23
103900   49
103901   30
103902   22
103903   27

[103904 rows x 1 columns]

In [12]:
df[["Age","Class"]]

        Age     Class
0        13  Eco Plus
1        25  Business
2        26  Business
3        25  Business
4        61  Business
...     ...       ...
103899   23       Eco
103900   49  Business
103901   30  Business
103902   22       Eco
103903   27  Business

[103904 rows x 2 columns]

In [13]:
df["Customer Type"].unique()

<StringArray>
['Loyal Customer', 'disloyal Customer']
Length: 2, dtype: str

In [14]:
df["Customer Type"].nunique()

2

In [15]:
df["Customer Type"].value_counts()

Customer Type
Loyal Customer       84923
disloyal Customer    18981
Name: count, dtype: int64

In [16]:
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
103899    False
103900    False
103901    False
103902    False
103903    False
Length: 103904, dtype: bool