In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\Hp\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\Hp\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Hp\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Hp\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\Hp\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\Hp\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\Hp\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Hp\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Hp\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\Hp\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

***Pandas***                                  

Pandas is a powerful Python library used for:                                                   

* Data analysis
* Data cleaning
* Working with tables (Excel/CSV data)
* Handling large datasets

It is one of the most important libraries in:                                                                

* Data Science
* Machine Learning
* AI
* Data Analytics

In [3]:
import os
import numpy as np
import pandas as pd

In [4]:
#######df=data frame

In [5]:
df=pd.read_csv(r"C:\Users\Hp\Downloads\Used_Bikes.csv")

In [6]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  str
 1   price       32648 non-null  float64
 2   city        32648 non-null  str
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  str
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  str
dtypes: float64(4), str(4)
memory usage: 2.0 MB

In [8]:
df.columns

Index(['bike_name', 'price', 'city', 'kms_driven', 'owner', 'age', 'power',
       'brand'],
      dtype='str')

In [9]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
32643     True
32644     True
32645     True
32646     True
32647     True
Length: 32648, dtype: bool

In [10]:
df.duplicated().sum()

np.int64(25324)

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [14]:
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [15]:
df.dropna(inplace=True)

ENCODING(sr--->num)

In [16]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7324 non-null   str
 1   price       7324 non-null   float64
 2   city        7324 non-null   str
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   str
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   str
dtypes: float64(4), str(4)
memory usage: 515.0 KB

In [17]:
df["owner"].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [18]:
owner_dict={
    'First Owner':1,'Second Owner':2,'Third Owner':3,'Fourth Owner':4
}

In [19]:
# df['owner']=df['owner'].map(owner_dict)

In [20]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [21]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7324 non-null   str
 1   price       7324 non-null   float64
 2   city        7324 non-null   str
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   str
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   str
dtypes: float64(4), str(4)
memory usage: 515.0 KB

In [22]:
df.tail(15)

,bike_name,price,city,kms_driven,owner,age,power,brand
9343,Hero Passion Plus 100cc,24000.0,Hyderabad,68000.0,First Owner,14.0,100.0,Hero
9344,Royal Enfield Bullet Twinspark 350cc,80000.0,Delhi,56968.0,First Owner,8.0,350.0,Royal Enfield
9345,Yamaha Fazer FI V 2.0 150cc,78000.0,Kanchipuram,7500.0,First Owner,3.0,150.0,Yamaha
9346,Honda CBR 150R 150cc,61483.0,Kanpur,28032.0,First Owner,7.0,150.0,Honda
9347,Bajaj Discover 125cc,14000.0,Mumbai,39211.0,First Owner,16.0,125.0,Bajaj
9348,KTM Duke 390cc,195000.0,Mumbai,4568.0,First Owner,4.0,390.0,KTM
9349,Bajaj Pulsar 180cc,55000.0,Pune,10000.0,First Owner,6.0,180.0,Bajaj
9350,Bajaj Pulsar NS200,46000.0,Bangalore,27687.0,Third Owner,9.0,200.0,Bajaj
9360,Bajaj Pulsar NS200,48000.0,Allahabad,41939.0,First Owner,8.0,200.0,Bajaj
9361,Bajaj Avenger 220cc,50000.0,Bangalore,29134.0,First Owner,7.0,220.0,Bajaj
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [23]:
####decoding :int ko string m convert krna 
####encoding : string ko int m convert krna

In [24]:
# df.drop('city',axis=1,inplace=True)#axis=1 ka meaning cloumn #axis=0 meaning row
####column permanent delete yah drop krna

In [25]:
# obj_val=df.select_dtypes(include='O')

In [26]:
# obj_val

In [27]:
# num=df.select_dtypes(exclude='O')

In [28]:
# df

In [29]:
# num

In [30]:
# complete_data=pd.concat([obj_val , num] , axis=1)

In [31]:
# complete_data

In [32]:
# df

FILTERING

find out bikes with TVS brand,owner,age  <=2

In [33]:
tvs_brand=df[df['brand']=='TVS']

In [34]:
tvs_brand

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
52,TVS Apache RTR 160cc,60000.0,Mumbai,30000.0,First Owner,5.0,160.0,TVS
114,TVS Apache RTR 160 4V Disc,69900.0,Delhi,8700.0,First Owner,3.0,160.0,TVS
130,TVS Phoenix Disc 125cc,21500.0,Barasat,10500.0,First Owner,5.0,125.0,TVS
...,...,...,...,...,...,...,...,...
9247,TVS Apache RTR 160cc Rear Disc,70000.0,Ghaziabad,4116.0,First Owner,3.0,160.0,TVS
9307,TVS Apache RTR 160cc,30000.0,Alibag,30000.0,First Owner,10.0,160.0,TVS
9312,TVS Apache RTR 200 4V FI,65450.0,Delhi,9238.0,First Owner,3.0,200.0,TVS
9320,TVS Apache 150cc,20000.0,Hissar,84916.0,First Owner,14.0,150.0,TVS
9322,TVS Radeon 110cc Drum SBT,58000.0,Delhi,4020.0,First Owner,2.0,110.0,TVS

In [35]:
tvs_first_owner= tvs_brand[tvs_brand['owner']=='First Owner']

In [36]:
tvs_age = tvs_first_owner[tvs_first_owner['age']<=2]
tvs_age

,bike_name,price,city,kms_driven,owner,age,power,brand
193,TVS Apache RTR 160 4V DISC ABS BS6,85000.0,Hyderabad,16000.0,First Owner,2.0,160.0,TVS
360,TVS Apache RTR 160 4V Disc,78700.0,Rudrapur,3710.0,First Owner,2.0,160.0,TVS
401,TVS Apache RTR 200 4V ABS Race Edition,108500.0,Delhi,10000.0,First Owner,2.0,200.0,TVS
425,TVS Apache RTR 160 4V DISC ABS,87000.0,Delhi,7000.0,First Owner,2.0,160.0,TVS
511,TVS Apache RTR 160 4V DRUM ABS,85000.0,Gurgaon,7000.0,First Owner,2.0,160.0,TVS
594,TVS Apache RTR 160 4V DISC ABS,91800.0,Delhi,1050.0,First Owner,2.0,160.0,TVS
664,TVS Apache RTR 160 4V DISC ABS,89000.0,Delhi,3000.0,First Owner,2.0,160.0,TVS
757,TVS Apache RTR 160 4V Disc,74700.0,Gautam Buddha Nagar,20194.0,First Owner,2.0,160.0,TVS
1097,TVS Apache RTR 200 4V Carburetor Race Edition 2.0,93500.0,Bangalore,2500.0,First Owner,2.0,200.0,TVS
1126,TVS Apache RTR 200 4V Dual Channel ABS BS6,130000.0,Bangalore,1300.0,First Owner,1.0,200.0,TVS
1132,TVS Apache RTR 160 4V DISC ABS BS6,98000.0,Jaipur,749.0,First Owner,1.0,160.0,TVS
1171,TVS Apache RR310,200000.0,Mumbai,4400.0,First Owner,2.0,310.0,TVS
1318,TVS Apache RTR 200 4V ABS Race Edition,125000.0,Hyderabad,530.0,First Owner,2.0,200.0,TVS
1514,TVS Apache RTR 160cc Matt Red Rear Disc,76000.0,Delhi,8000.0,First Owner,2.0,160.0,TVS
1678,TVS Apache RTR 200 4V Carburetor Pirelli Tyres...,122000.0,Chennai,3100.0,First Owner,2.0,200.0,TVS
1712,TVS Apache RR310 Slipper Clutch,224000.0,Vadodara,3900.0,First Owner,2.0,310.0,TVS
1741,TVS Apache RTR 200 4V Carburetor Pirelli Tyres...,98500.0,Delhi,2800.0,First Owner,2.0,200.0,TVS
1762,TVS Apache RTR 160 4V DISC ABS,89135.0,Delhi,2800.0,First Owner,2.0,160.0,TVS
1802,TVS Apache RTR 180cc,88000.0,Gurgaon,900.0,First Owner,2.0,180.0,TVS
2325,TVS Apache RTR 200 4V ABS,92000.0,Mumbai,4500.0,First Owner,2.0,200.0,TVS
2360,TVS Victor 110cc Disc SBT,54000.0,Delhi,6000.0,First Owner,2.0,110.0,TVS
2415,TVS Apache RTR 160 4V DISC ABS,85000.0,Delhi,11496.0,First Owner,2.0,160.0,TVS
3071,TVS Apache RTR 160 4V DISC ABS,94000.0,Ahmedabad,893.0,First Owner,2.0,160.0,TVS
3178,TVS Apache RTR 160cc White Race Edition Rear Disc,82000.0,Bangalore,52198.0,First Owner,2.0,160.0,TVS
3333,TVS Apache RTR 160 4V Carburetor With Rear Disc,85000.0,Mumbai,6821.0,First Owner,2.0,160.0,TVS
3440,TVS Apache RTR 160 4V Disc,92000.0,Mumbai,14289.0,First Owner,2.0,160.0,TVS
4251,TVS Star City Plus 110cc,51000.0,Ahmedabad,12000.0,First Owner,2.0,110.0,TVS
4367,TVS Apache RTR 160 4V Carburetor,90000.0,Ghaziabad,2672.0,First Owner,2.0,160.0,TVS
5506,TVS Apache RTR 200 4V ABS Race Edition,106000.0,Delhi,1890.0,First Owner,2.0,200.0,TVS
5510,TVS Apache RTR 180cc,90000.0,Ghaziabad,3095.0,First Owner,2.0,180.0,TVS
5557,TVS Apache RTR 200 4V FI,102000.0,Thane,8120.0,First Owner,2.0,200.0,TVS
5805,TVS Apache RTR 200 4V ABS Race Edition,128000.0,Bangalore,4000.0,First Owner,2.0,200.0,TVS
6003,TVS Apache RTR 160 4V Carburetor,90700.0,Delhi,900.0,First Owner,2.0,160.0,TVS
6058,TVS Apache RR310,220000.0,Noida,5432.0,First Owner,2.0,310.0,TVS
6571,TVS Apache RTR 160 4V Carburetor,86000.0,Faridabad,15228.0,First Owner,2.0,160.0,TVS
6787,TVS Apache RTR 200 4V Race Edition 2.0,106000.0,Mumbai,7157.0,First Owner,2.0,200.0,TVS
7055,TVS Sport 100cc,46000.0,Faridabad,6222.0,First Owner,2.0,100.0,TVS
7311,TVS Apache RTR 180cc,70000.0,Jaipur,207102.0,First Owner,2.0,180.0,TVS
8883,TVS Apache RTR 200 4V ABS Race Edition,120000.0,Mumbai,4442.0,First Owner,2.0,200.0,TVS
9322,TVS Radeon 110cc Drum SBT,58000.0,Delhi,4020.0,First Owner,2.0,110.0,TVS

In [37]:
tvs_age

,bike_name,price,city,kms_driven,owner,age,power,brand
193,TVS Apache RTR 160 4V DISC ABS BS6,85000.0,Hyderabad,16000.0,First Owner,2.0,160.0,TVS
360,TVS Apache RTR 160 4V Disc,78700.0,Rudrapur,3710.0,First Owner,2.0,160.0,TVS
401,TVS Apache RTR 200 4V ABS Race Edition,108500.0,Delhi,10000.0,First Owner,2.0,200.0,TVS
425,TVS Apache RTR 160 4V DISC ABS,87000.0,Delhi,7000.0,First Owner,2.0,160.0,TVS
511,TVS Apache RTR 160 4V DRUM ABS,85000.0,Gurgaon,7000.0,First Owner,2.0,160.0,TVS
594,TVS Apache RTR 160 4V DISC ABS,91800.0,Delhi,1050.0,First Owner,2.0,160.0,TVS
664,TVS Apache RTR 160 4V DISC ABS,89000.0,Delhi,3000.0,First Owner,2.0,160.0,TVS
757,TVS Apache RTR 160 4V Disc,74700.0,Gautam Buddha Nagar,20194.0,First Owner,2.0,160.0,TVS
1097,TVS Apache RTR 200 4V Carburetor Race Edition 2.0,93500.0,Bangalore,2500.0,First Owner,2.0,200.0,TVS
1126,TVS Apache RTR 200 4V Dual Channel ABS BS6,130000.0,Bangalore,1300.0,First Owner,1.0,200.0,TVS
1132,TVS Apache RTR 160 4V DISC ABS BS6,98000.0,Jaipur,749.0,First Owner,1.0,160.0,TVS
1171,TVS Apache RR310,200000.0,Mumbai,4400.0,First Owner,2.0,310.0,TVS
1318,TVS Apache RTR 200 4V ABS Race Edition,125000.0,Hyderabad,530.0,First Owner,2.0,200.0,TVS
1514,TVS Apache RTR 160cc Matt Red Rear Disc,76000.0,Delhi,8000.0,First Owner,2.0,160.0,TVS
1678,TVS Apache RTR 200 4V Carburetor Pirelli Tyres...,122000.0,Chennai,3100.0,First Owner,2.0,200.0,TVS
1712,TVS Apache RR310 Slipper Clutch,224000.0,Vadodara,3900.0,First Owner,2.0,310.0,TVS
1741,TVS Apache RTR 200 4V Carburetor Pirelli Tyres...,98500.0,Delhi,2800.0,First Owner,2.0,200.0,TVS
1762,TVS Apache RTR 160 4V DISC ABS,89135.0,Delhi,2800.0,First Owner,2.0,160.0,TVS
1802,TVS Apache RTR 180cc,88000.0,Gurgaon,900.0,First Owner,2.0,180.0,TVS
2325,TVS Apache RTR 200 4V ABS,92000.0,Mumbai,4500.0,First Owner,2.0,200.0,TVS
2360,TVS Victor 110cc Disc SBT,54000.0,Delhi,6000.0,First Owner,2.0,110.0,TVS
2415,TVS Apache RTR 160 4V DISC ABS,85000.0,Delhi,11496.0,First Owner,2.0,160.0,TVS
3071,TVS Apache RTR 160 4V DISC ABS,94000.0,Ahmedabad,893.0,First Owner,2.0,160.0,TVS
3178,TVS Apache RTR 160cc White Race Edition Rear Disc,82000.0,Bangalore,52198.0,First Owner,2.0,160.0,TVS
3333,TVS Apache RTR 160 4V Carburetor With Rear Disc,85000.0,Mumbai,6821.0,First Owner,2.0,160.0,TVS
3440,TVS Apache RTR 160 4V Disc,92000.0,Mumbai,14289.0,First Owner,2.0,160.0,TVS
4251,TVS Star City Plus 110cc,51000.0,Ahmedabad,12000.0,First Owner,2.0,110.0,TVS
4367,TVS Apache RTR 160 4V Carburetor,90000.0,Ghaziabad,2672.0,First Owner,2.0,160.0,TVS
5506,TVS Apache RTR 200 4V ABS Race Edition,106000.0,Delhi,1890.0,First Owner,2.0,200.0,TVS
5510,TVS Apache RTR 180cc,90000.0,Ghaziabad,3095.0,First Owner,2.0,180.0,TVS
5557,TVS Apache RTR 200 4V FI,102000.0,Thane,8120.0,First Owner,2.0,200.0,TVS
5805,TVS Apache RTR 200 4V ABS Race Edition,128000.0,Bangalore,4000.0,First Owner,2.0,200.0,TVS
6003,TVS Apache RTR 160 4V Carburetor,90700.0,Delhi,900.0,First Owner,2.0,160.0,TVS
6058,TVS Apache RR310,220000.0,Noida,5432.0,First Owner,2.0,310.0,TVS
6571,TVS Apache RTR 160 4V Carburetor,86000.0,Faridabad,15228.0,First Owner,2.0,160.0,TVS
6787,TVS Apache RTR 200 4V Race Edition 2.0,106000.0,Mumbai,7157.0,First Owner,2.0,200.0,TVS
7055,TVS Sport 100cc,46000.0,Faridabad,6222.0,First Owner,2.0,100.0,TVS
7311,TVS Apache RTR 180cc,70000.0,Jaipur,207102.0,First Owner,2.0,180.0,TVS
8883,TVS Apache RTR 200 4V ABS Race Edition,120000.0,Mumbai,4442.0,First Owner,2.0,200.0,TVS
9322,TVS Radeon 110cc Drum SBT,58000.0,Delhi,4020.0,First Owner,2.0,110.0,TVS

In [38]:
# dup>null value >str>num>drop

In [39]:
# df.isnull().sum()

In [40]:
# df.info()

In [41]:
# df.dropna(inplace=True)

In [42]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [43]:
# df.info()

In [44]:
# df['bike_name'].unique()

In [45]:
bike_name_dict={
    'TVS Star City Plus Dual Tone 110cc':1,
              'Royal Enfield Classic 350cc':2,
                     'Triumph Daytona 675R':3,
                     'TVS Apache RTR 180cc':4,
     'Yamaha FZ S V 2.0 150cc-Ltd. Edition':5,
                         'Yamaha FZs 150cc':6,
            'Honda CB Hornet 160R  ABS DLX':7,
      'Hero Splendor Plus Self Alloy 100cc':8,
        'Royal Enfield Thunderbird X 350cc':9,
 'Royal Enfield Classic Desert Storm 500cc':10,
 
                 'Bajaj Discover150S 150cc':11,
                       'Hero i Smart 125cc':12,
               'Hero Splendor Plus  100 cc':13,
                'Hero Splendor Plus 100 CC':14,
                      'Hero Karizma 223 cc':15,
                         'TVS MAX 4R 110cc':16,
                   'Mahindra Pantero 110cc':17,
                      'Hero Ambition 135cc':18,
                'Honda CBR 250R Repsol ABS':19,
                'Hero Hunk Rear Disc 150cc':20
             
}

In [46]:
# df['bike_name']= df['bike_name'].map(bike_name_dict)

In [47]:
# df

In [48]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [49]:
tvs_brand=df[df['brand']=='TVS']

In [50]:
tvs_under2 =tvs_brand[tvs_brand['age']<=2]

In [51]:
tvs_under2[tvs_under2['kms_driven']<2000]

,bike_name,price,city,kms_driven,owner,age,power,brand
594,TVS Apache RTR 160 4V DISC ABS,91800.0,Delhi,1050.0,First Owner,2.0,160.0,TVS
1126,TVS Apache RTR 200 4V Dual Channel ABS BS6,130000.0,Bangalore,1300.0,First Owner,1.0,200.0,TVS
1132,TVS Apache RTR 160 4V DISC ABS BS6,98000.0,Jaipur,749.0,First Owner,1.0,160.0,TVS
1318,TVS Apache RTR 200 4V ABS Race Edition,125000.0,Hyderabad,530.0,First Owner,2.0,200.0,TVS
1802,TVS Apache RTR 180cc,88000.0,Gurgaon,900.0,First Owner,2.0,180.0,TVS
3071,TVS Apache RTR 160 4V DISC ABS,94000.0,Ahmedabad,893.0,First Owner,2.0,160.0,TVS
5506,TVS Apache RTR 200 4V ABS Race Edition,106000.0,Delhi,1890.0,First Owner,2.0,200.0,TVS
6003,TVS Apache RTR 160 4V Carburetor,90700.0,Delhi,900.0,First Owner,2.0,160.0,TVS

In [52]:
royal_enfield_brand=df[df['brand']=='Royal Enfield']

In [53]:
royal_enfield_under2=royal_enfield_brand[royal_enfield_brand['age']<=2]

In [54]:
royal_enfield_under2[royal_enfield_under2['kms_driven']<2000]

,bike_name,price,city,kms_driven,owner,age,power,brand
277,Royal Enfield Interceptor 650cc,280000.0,Bangalore,1500.0,First Owner,2.0,650.0,Royal Enfield
850,Royal Enfield Himalayan 410cc Fi ABS,180000.0,Guwahati,200.0,First Owner,2.0,410.0,Royal Enfield
962,Royal Enfield Thunderbird X 350cc ABS,155000.0,Vadodara,1650.0,First Owner,2.0,350.0,Royal Enfield
1203,Royal Enfield Classic Gunmetal Grey 350cc ABS,150000.0,Bardhaman,1800.0,First Owner,2.0,350.0,Royal Enfield
1251,Royal Enfield Interceptor 650cc,250000.0,Silchar,920.0,First Owner,2.0,650.0,Royal Enfield
1716,Royal Enfield Thunderbird 350cc ABS,144700.0,Kharar,770.0,First Owner,2.0,350.0,Royal Enfield
1796,Royal Enfield Himalayan 410cc Fi ABS,166000.0,Guwahati,250.0,First Owner,2.0,410.0,Royal Enfield
2929,Royal Enfield Himalayan 410cc Fi ABS,184000.0,Bardhaman,1380.0,First Owner,2.0,410.0,Royal Enfield
3089,Royal Enfield Classic Desert Storm 500cc Dual ...,239000.0,Mumbai,1264.0,First Owner,2.0,500.0,Royal Enfield
3166,Royal Enfield Thunderbird X 350cc ABS,160000.0,Delhi,1189.0,First Owner,2.0,350.0,Royal Enfield
5133,Royal Enfield Thunderbird X 350cc ABS,170000.0,Gurgaon,500.0,First Owner,2.0,350.0,Royal Enfield
5495,Royal Enfield Classic 350cc,150000.0,Kota,1947.0,First Owner,2.0,350.0,Royal Enfield
5703,Royal Enfield Himalayan 410cc Fi ABS,194000.0,Thane,844.0,First Owner,2.0,410.0,Royal Enfield
6022,Royal Enfield Classic Gunmetal Grey 350cc ABS,161100.0,Guwahati,1753.0,First Owner,2.0,350.0,Royal Enfield
6090,Royal Enfield Bullet Electra Twinspark 350CC ABS,127000.0,Mumbai,83.0,First Owner,2.0,350.0,Royal Enfield
6283,Royal Enfield Himalayan 410cc Sleet ABS,175000.0,Alipore,1800.0,First Owner,2.0,410.0,Royal Enfield
7294,Royal Enfield Classic 350cc-Redditch Edition,133500.0,Mumbai,1608.0,First Owner,2.0,350.0,Royal Enfield
7694,Royal Enfield Classic Chrome 500cc ABS,215000.0,Delhi,417.0,First Owner,2.0,500.0,Royal Enfield
8836,Royal Enfield Thunderbird X 350cc ABS,170200.0,Mumbai,1000.0,First Owner,2.0,350.0,Royal Enfield

In [55]:
royal_enfield_under2[royal_enfield_under2['price']<150000]

,bike_name,price,city,kms_driven,owner,age,power,brand
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,First Owner,2.0,350.0,Royal Enfield
1006,Royal Enfield Thunderbird 350cc ABS,148000.0,Haldwani,7300.0,First Owner,2.0,350.0,Royal Enfield
1681,Royal Enfield Thunderbird X 350cc ABS,135000.0,Sibsagar,3800.0,First Owner,2.0,350.0,Royal Enfield
1716,Royal Enfield Thunderbird 350cc ABS,144700.0,Kharar,770.0,First Owner,2.0,350.0,Royal Enfield
1749,Royal Enfield Bullet Twinspark Kickstart 350cc,145000.0,Delhi,5000.0,First Owner,2.0,350.0,Royal Enfield
2982,Royal Enfield Classic 350cc-Redditch Edition,137000.0,Sultanpur,8400.0,First Owner,2.0,350.0,Royal Enfield
5939,Royal Enfield Bullet Twinspark Kickstart 350cc,105000.0,Faridabad,7255.0,First Owner,2.0,350.0,Royal Enfield
6090,Royal Enfield Bullet Electra Twinspark 350CC ABS,127000.0,Mumbai,83.0,First Owner,2.0,350.0,Royal Enfield
6298,Royal Enfield Bullet Electra Twinspark 350CC ABS,140000.0,Mumbai,2000.0,First Owner,2.0,350.0,Royal Enfield
6329,Royal Enfield Electra 350cc,130000.0,Faridabad,3688.0,First Owner,2.0,350.0,Royal Enfield
6590,Royal Enfield Classic 350cc,130000.0,Ghaziabad,19249.0,First Owner,2.0,350.0,Royal Enfield
7019,Royal Enfield Electra 350cc,135000.0,Ahmedabad,10779.0,First Owner,2.0,350.0,Royal Enfield
7294,Royal Enfield Classic 350cc-Redditch Edition,133500.0,Mumbai,1608.0,First Owner,2.0,350.0,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000.0,Ghaziabad,12400.0,First Owner,2.0,350.0,Royal Enfield

In [56]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [57]:
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [58]:
df[(df['brand']=='Royal Enfield') & (df["age"]<=2) & (df['price']<=150000)]

,bike_name,price,city,kms_driven,owner,age,power,brand
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,First Owner,2.0,350.0,Royal Enfield
479,Royal Enfield Classic 350cc,150000.0,Delhi,4000.0,First Owner,2.0,350.0,Royal Enfield
1006,Royal Enfield Thunderbird 350cc ABS,148000.0,Haldwani,7300.0,First Owner,2.0,350.0,Royal Enfield
1203,Royal Enfield Classic Gunmetal Grey 350cc ABS,150000.0,Bardhaman,1800.0,First Owner,2.0,350.0,Royal Enfield
1681,Royal Enfield Thunderbird X 350cc ABS,135000.0,Sibsagar,3800.0,First Owner,2.0,350.0,Royal Enfield
1716,Royal Enfield Thunderbird 350cc ABS,144700.0,Kharar,770.0,First Owner,2.0,350.0,Royal Enfield
1749,Royal Enfield Bullet Twinspark Kickstart 350cc,145000.0,Delhi,5000.0,First Owner,2.0,350.0,Royal Enfield
2982,Royal Enfield Classic 350cc-Redditch Edition,137000.0,Sultanpur,8400.0,First Owner,2.0,350.0,Royal Enfield
5495,Royal Enfield Classic 350cc,150000.0,Kota,1947.0,First Owner,2.0,350.0,Royal Enfield
5939,Royal Enfield Bullet Twinspark Kickstart 350cc,105000.0,Faridabad,7255.0,First Owner,2.0,350.0,Royal Enfield
6090,Royal Enfield Bullet Electra Twinspark 350CC ABS,127000.0,Mumbai,83.0,First Owner,2.0,350.0,Royal Enfield
6298,Royal Enfield Bullet Electra Twinspark 350CC ABS,140000.0,Mumbai,2000.0,First Owner,2.0,350.0,Royal Enfield
6329,Royal Enfield Electra 350cc,130000.0,Faridabad,3688.0,First Owner,2.0,350.0,Royal Enfield
6590,Royal Enfield Classic 350cc,130000.0,Ghaziabad,19249.0,First Owner,2.0,350.0,Royal Enfield
7019,Royal Enfield Electra 350cc,135000.0,Ahmedabad,10779.0,First Owner,2.0,350.0,Royal Enfield
7294,Royal Enfield Classic 350cc-Redditch Edition,133500.0,Mumbai,1608.0,First Owner,2.0,350.0,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000.0,Ghaziabad,12400.0,First Owner,2.0,350.0,Royal Enfield

In [59]:
df.query("brand=='Royal Enfield' and age <=2")

,bike_name,price,city,kms_driven,owner,age,power,brand
38,Royal Enfield Thunderbird X 500cc,190500.0,Samastipur,4550.0,First Owner,2.0,500.0,Royal Enfield
81,Royal Enfield Interceptor 650cc,260000.0,Navi Mumbai,3800.0,First Owner,2.0,650.0,Royal Enfield
139,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,First Owner,2.0,410.0,Royal Enfield
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,First Owner,2.0,350.0,Royal Enfield
222,Royal Enfield Himalayan 410cc Fi ABS,177982.0,Hamirpur(hp),7000.0,First Owner,2.0,410.0,Royal Enfield
...,...,...,...,...,...,...,...,...
7294,Royal Enfield Classic 350cc-Redditch Edition,133500.0,Mumbai,1608.0,First Owner,2.0,350.0,Royal Enfield
7694,Royal Enfield Classic Chrome 500cc ABS,215000.0,Delhi,417.0,First Owner,2.0,500.0,Royal Enfield
8139,Royal Enfield Thunderbird X 350cc ABS,169000.0,Bangalore,4411.0,First Owner,2.0,350.0,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000.0,Ghaziabad,12400.0,First Owner,2.0,350.0,Royal Enfield
8836,Royal Enfield Thunderbird X 350cc ABS,170200.0,Mumbai,1000.0,First Owner,2.0,350.0,Royal Enfield

In [60]:
x=df.drop('price',axis=1)

In [61]:
y=df[['price']]

In [62]:
y

         price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
9362   25000.0
9369   35000.0
9370  450000.0
9371  139000.0
9372   80000.0

[7324 rows x 1 columns]

In [63]:
x

,bike_name,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [64]:
df.to_csv("clean_bike_data.csv")

In [65]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj